name: CD - Flutter Main

on:
  push:
    branches:
      - main

jobs:
  build_release_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkoout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'
          cache: true

      - run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        run: actions/upload-artifact@v4
        with:
          name: main-apk
          path: build/app/outputs/flutter-apk/app-release.apk

